---
# defaults file for jenkins-k8s

# Jenkins version
jenkins_image: "jenkins/jenkins:2.555.1-jdk21"

# Resource limits
jenkins_cpu_request: "100m"
jenkins_memory_request: "512Mi"
jenkins_cpu_limit: "1000m"
jenkins_memory_limit: "1Gi"

# Java options
jenkins_java_opts: "-Xmx512m -Xms256m"

# Service configuration
jenkins_nodeport: 30080
jenkins_namespace: "jenkins"
