---
- name: Setup Tools VM with Docker, kubectl, Helm, Nexus, Nexus Registry, and Gitea
  hosts: tools
  become: true
  roles:
    - ../roles/docker
    - ../roles/kubectl
    - ../roles/helm
    - ../roles/nexus
    - ../roles/nexus-docker-registry
    - ../roles/gitea
