---
- name: Setup Tools VM with Docker, kubectl, Helm, Nexus, Nexus Registry, and Gitea
  hosts: tools
  become: true
  roles:
    - role: ../roles/docker
      tags: docker
    - role: ../roles/kubectl
      tags: kubectl
    - role: ../roles/helm
      tags: helm
    - role: ../roles/nexus
      tags: nexus
    - role: ../roles/nexus-docker-registry
      tags: nexus-registry
    - role: ../roles/gitea
      tags: gitea
